import { Home } from 'lucide-react';

export function Footer() {
  return (
    <footer className="border-t border-black/5 py-12 px-8 mt-20">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 bg-emerald-600 rounded flex items-center justify-center">
            <Home className="text-white w-4 h-4" />
          </div>
          <span className="font-bold tracking-tight">ArchAI</span>
        </div>
        <div className="text-sm text-black/40">© 2026 ArchAI. Conceptual designs generated by AI.</div>
        <div className="flex gap-6 text-sm font-medium opacity-60">
          <a href="#" className="hover:opacity-100">
            Privacy
          </a>
          <a href="#" className="hover:opacity-100">
            Terms
          </a>
          <a href="#" className="hover:opacity-100">
            Contact
          </a>
        </div>
      </div>
    </footer>
  );
}
